[package]
name = "rpwgen"
version = "0.1.0"
authors = ["Kuroki Keiichiro <kerog0821@gmail.com>"]

[dependencies]
rand = "0.6.1"
clap = "~2.29.0"
unic-char-range ="~0.8.0"

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "generate"
harness = false
